name: splitty
description: The Pretty Bill Splitting App

publish_to: 'none'
version: 1.0.2+3

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_native_splash: ^2.2.8
  pinput: ^3.0.1
  flutter_riverpod: ^2.0.0-dev.9
  cached_network_image: ^3.2.1
  intl_phone_field: ^3.1.0
  url_launcher: ^6.1.4
  timeago: ^3.3.0

  firebase_core: ^2.21.0
  firebase_auth: ^4.12.1
  cloud_firestore: ^4.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_foreground: "assets/icon-foreground.png"
  adaptive_icon_background: "assets/icon-background.png"

flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: outfit
      fonts:
        - asset: assets/fonts/outfit/Outfit-Regular.ttf
        - asset: assets/fonts/outfit/Outfit-Medium.ttf
          weight: 500
        - asset: assets/fonts/outfit/Outfit-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/outfit/Outfit-Bold.ttf
          weight: 700